### ISSUE TITLE
Please clarify release files in v0.5.0

### ISSUE THREAD

**Issue by SuhasSrinivasan** [nanoporetech/modkit#473]
Dear ONT Developers,

Thank you for developing modkit.

In the latest v0.5.0 release, there are multiple compiled binaries available and the file names are not descriptive enough to understand which one should be used.
Additionally, the [Quick Start Guide](https://nanoporetech.github.io/modkit/) does not contain any information to aid the installation.
There is also no relevant documentation in the GitHub README.

It will be helpful to know the differences in the binaries and which is the recommended binary to use.

**Comment by ArtRand** [comment]
Hello @SuhasSrinivasan, 

There is a mention of the different versions in the [open chromatin documentation](https://nanoporetech.github.io/modkit/intro_open_chromatin.html#running-with-a-gpu) but I agree that it could be more useful. The README could also use a refresh. 

Generally here is the breakdown of which build to use:

If you have a GPU: Use either the candle or tch releases of Modkit (candle: https://github.com/nanoporetech/modkit/releases/download/v0.5.0/modkit_v0.5.0_u20_x86_64_candle.tar.gz, tch: https://github.com/nanoporetech/modkit/releases/download/v0.5.0/modkit_v0.5.0_u20_x86_64_tch.tar.gz).

The GPU versions are quite quite a bit quicker than the CPU version, the tch version especially. The trade-off between tch and candle when using a GPU is that the tch version requires you to download torchlib and set some environment variables. There are some instructions [here](https://github.com/nanoporetech/modkit/blob/master/BUILD_NOTES_tch.txt). The candle version on the other hand doesn't require anything, but is 1.5-3x slower than the tch version. You don't need a fancy GPU to run this command, I use the oldest ones on our cluster and it's fine for small tests. For large runs, bigger/newer is better but that shouldn't be surprising.

If you don't have a GPU, and must run on the CPU, the only real usable version is the tch version with this flag: --device cpu .
The generic release (https://github.com/nanoporetech/modkit/releases/download/v0.5.0/modkit_v0.5.0_u16_x86_64.tar.gz) and the candle version are unfortunately quite slow on the CPU, the tch version is a lot faster (even on CPU). I'm working on better work-arounds here.

If you must run on CPU and don't/cant get torchlib downloaded, the generic release is probably slightly better than the candle one.

If you're compiling on MacOS and want to use tch, I have some scripts I can give you.

The `open-chromatin` function in Modkit is new, I'm more than happy to answer any questions you may have.

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand 
Thank you for reviewing and the detailed response to the query!
I will setup the necessary requirements and try the `tch` binary in a Ubuntu 22.04 environment.

Since **dorado** has native support through PyTorch and Metal Performance Shaders, are there plans to provide a macOS binary for modkit? Would be very helpful!

**Comment by ArtRand** [comment]
Hello @SuhasSrinivasan, 

> Since dorado has native support through PyTorch and Metal Performance Shaders, are there plans to provide a macOS binary for modkit?

If there is sufficient users who need a macOS binary with `tch` I can look into doing this. Distributing macOS binaries requires Mac CI infrastructure as you can imagine. On the other hand, building on Mac with `cargo` is pretty easy (I develop Modkit on a Mac). 

If you clone the repo and run `cargo run --release --features accelerate,tch -- open-chromatin predict`, you will build a version that can use the `--device mps` option to leverage the Mac GPU. When you use `cargo run` it takes care of a lot of the annoyance around getting the libtorch and informing Modkit where it is.

However, if you run the build artifact you may get an error like this:

```text
dyld[14815]: Library not loaded: @rpath/libtorch_cpu.dylib
  Referenced from: <50155C59-DCFC-3338-A892-A3D4AF618D0E> /Users/art.rand/projects/mod_flatten/target/debug/modkit
  Reason: no LC_RPATH's found
[1]    14815 abort      target/debug/modkit
```

There are a couple ways to deal with this, both are pretty easy. 

The first way requires you to have some kind of python environment to get pytorch. 

```bash
$ python -m venv venv
$ . venv/bin/activate 
$ pip install --upgrade pip
$ pip install torch
```

Then set these environment variables: 
```bash
export LIBTORCH_USE_PYTORCH=1
export LIBTORCH=/full/path/to/venv/lib/python3.11/site-packages/torch
export DYLD_LIBRARY_PATH=/full/path/to/venv/lib/python3.11/site-packages/torch/lib
```
Replace `python3.11` with the python version you have. Then the build in `target/release` should pick up libtorch and "just work".

The second, no-python, way is to search the `target/[debug|release]` directory for the directory containing `libtorch.dylib`, on my machine it is `/Users/art.rand/projects/mod_flatten/target/release/build/torch-sys-e16d1d6bba7288bc/out/libtorch/libtorch/lib` for a particular build. Then set the `DYLC_LIBRARY_PATH` to this location and run `modkit`:

```bash
$ DYLD_LIBRARY_PATH=/Users/art.rand/projects/mod_flatten/target/release/build/torch-sys-e16d1d6bba7288bc/out/libtorch/libtorch/lib ./target/release/modkit
```

You can also copy this directory somewhere and keep the environment variable in your `.zshrc` (this is what I do). The tch crate on which Modkit depends has some clever logic to download the libtorch version you want on Mac, so might as well use it.

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand 

Thank you very much again!
Completely understand the development & testing effort and CI infrastructure needed to support another OS.

Considering:
1. dorado has a binary with PyTorch MPS acceleration for Mac
2. Apple has listed ONT Dorado Basecalling in the 2025 Mac Studio-M3 Ultra product page! 😁

Hope to see a modkit macOS binary soon!

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand ,
Thank you for releasing v 0.6.0!
Are there any plans/timelines to release a macOS binary?

**Comment by ArtRand** [comment]
Hello @SuhasSrinivasan, 

Yes, it's on my TODOs. For what it's worth, there isn't a v0.6.0 release of the `tch` and `candle` builds since the open chromatin module has not changed for v0.6.0.

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand ,

Thank you and looking forward to it!
With Macs being so powerful with their CPU design and catching up with GPU design too, it will be great to have modkit support for Macs.

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand ,

It is no longer possible to compile with `rustc 1.93.0 (254b59607 2026-01-19)`.
Produces many errors.
It worked until `rustc 1.86.0`

**Comment by ArtRand** [comment]
Hello @SuhasSrinivasan, 

Modkit should be "pinned" to use 1.90.0 via the rust-toolchain.toml, see below:

```bash
❯ pwd
/Users/art.rand/projects/github/modkit
❯ rustc --version
rustc 1.90.0 (1159e78c4 2025-09-14)
# builds
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 30s
```

whereas: 

```bash
❯ pwd
/Users/art.rand
❯ rustc --version
rustc 1.93.0 (254b59607 2026-01-19)
```

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand ,

Thanks for this info.
I had only managed to get this compiled once on a Mac Studio, and it worked then (Dec 2025).

Earlier this week on a different Mac Studio I was getting Rust's unsafe compilation errors.
So I assumed it was because of the newer version of Rust I installed. 

But I wanted to recreate the issue to paste the exact error messages, however now I have a different error, please see below.
Did not encounter this back in December.

```
~/Downloads$ rustc --version
rustc 1.93.0 (254b59607 2026-01-19)
~/Downloads$ cargo --version
cargo 1.93.0 (083ac5135 2025-12-15)

~/Downloads/modkit-0.5.0$ rustc --version
rustc 1.86.0 (05f9846f8 2025-03-31)
~/Downloads/modkit-0.5.0$ cargo --version
cargo 1.86.0 (adf9b6ad1 2025-02-28)

~/Downloads/modkit-0.5.0$ cargo build --release --features accelerate,tch
    Updating crates.io index
     Locking 719 packages to latest compatible versions
      Adding bio v1.6.0 (available: v3.0.0)
      Adding burn v0.17.1 (available: v0.18.0)
      Adding charming v0.3.1 (available: v0.6.0)
      Adding cubecl-hip-sys v6.4.0 (available: v6.4.4348400)
      Adding darling v0.23.0 (requires Rust 1.88.0)
      Adding darling_core v0.23.0 (requires Rust 1.88.0)
      Adding darling_macro v0.23.0 (requires Rust 1.88.0)
      Adding derive-new v0.6.0 (available: v0.7.0)
      Adding generic-array v0.14.7 (available: v0.14.9)
      Adding gzp v0.11.3 (available: v2.0.2)
      Adding indicatif v0.17.11 (available: v0.18.3)
      Adding instability v0.3.11 (requires Rust 1.88)
      Adding itertools v0.12.1 (available: v0.14.0)
      Adding ndarray v0.15.6 (available: v0.17.2)
      Adding nom v7.1.3 (available: v8.0.0)
      Adding pulp v0.18.22 (available: v0.22.2)
      Adding rand v0.8.5 (available: v0.9.2)
      Adding rust-htslib v0.46.0 (available: v0.51.0)
      Adding rustc-hash v1.1.0 (available: v2.1.1)
      Adding rv v0.16.0 (available: v0.16.5)
      Adding statrs v0.16.1 (available: v0.18.0)
      Adding time v0.3.46 (requires Rust 1.88.0)
      Adding time-core v0.1.8 (requires Rust 1.88.0)
      Adding time-macros v0.2.26 (requires Rust 1.88.0)
      Adding unicode-width v0.2.0 (available: v0.2.2)
      Adding wasip2 v1.0.2+wasi-0.2.9 (requires Rust 1.87.0)
      Adding wit-bindgen v0.51.0 (requires Rust 1.87.0)
  Downloaded clap v4.5.55
  Downloaded zmij v1.0.17
  Downloaded uuid v1.20.0
  Downloaded time-macros v0.2.26
  Downloaded clap_derive v4.5.55
  Downloaded zerocopy v0.8.35
  Downloaded clap_builder v4.5.55
  Downloaded cc v1.2.54
  Downloaded time v0.3.46
  Downloaded num-conv v0.2.0
  Downloaded zerocopy-derive v0.8.35
  Downloaded iana-time-zone v0.1.65
  Downloaded time-core v0.1.8
  Downloaded libm v0.2.16
  Downloaded openssl-src v300.5.5+3.5.5
  Downloaded 15 crates (8.3 MB) in 0.97s (largest was `openssl-src` at 7.0 MB)
error: rustc 1.86.0 is not supported by the following packages:
  time@0.3.46 requires rustc 1.88.0
  time@0.3.46 requires rustc 1.88.0
  time-core@0.1.8 requires rustc 1.88.0
  time-core@0.1.8 requires rustc 1.88.0
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.86.0
```

Would be very helpful to get a binary for macOS 🙏

**Comment by ArtRand** [comment]
@SuhasSrinivasan I see, try deleting the `rust-toolchain.toml` from the repo and re-building?

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand ,
Thank you!
Deleting the `toml` started the compilation and finished with below warnings. 
These weren't there back in December (rustc 1.86).
```
warning: unused import: `arg`                                                                                                                                                                                                                                                                                                  12:38 [59/538]
 --> modkit-core/src/motifs/args.rs:1:12
  |
1 | use clap::{arg, Args};
  |            ^^^
  |
  = note: `#[warn(unused_imports)]` (part of `#[warn(unused)]`) on by default

warning: hiding a lifetime that's elided elsewhere is confusing
   --> modkit-core/src/entropy/mod.rs:595:29
    |
595 |     fn get_fetch_definition(&self) -> FetchDefinition {
    |                             ^^^^^     ^^^^^^^^^^^^^^^ the same lifetime is hidden here
    |                             |
    |                             the lifetime is elided here
    |
    = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
    = note: `#[warn(mismatched_lifetime_syntaxes)]` on by default
help: use `'_` for type paths
    |
595 |     fn get_fetch_definition(&self) -> FetchDefinition<'_> {
    |                                                      ++++

warning: hiding a lifetime that's elided elsewhere is confusing
  --> modkit-core/src/entropy/methylation_entropy.rs:67:19
   |
67 |     fn get_column(&self, idx: usize) -> Chars {
   |                   ^^^^^                 ^^^^^ the same lifetime is hidden here
   |                   |
   |                   the lifetime is elided here
   |
   = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
   |
67 |     fn get_column(&self, idx: usize) -> Chars<'_> {
   |                                              ++++

warning: hiding a lifetime that's elided elsewhere is confusing
   --> modkit-core/src/motifs/mod.rs:468:9
    |
468 |         &self,
    |         ^^^^^ the lifetime is elided here
...
473 |     ) -> Vec<(KmerRef, u32)> {
    |               ^^^^^^^ the same lifetime is hidden here
    |
    = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
    |
473 |     ) -> Vec<(KmerRef<'_>, u32)> {
    |                      ++++

warning: hiding a lifetime that's elided elsewhere is confusing
   --> modkit-core/src/motifs/mod.rs:708:9
    |
708 |         &self,
    |         ^^^^^ the lifetime is elided here
...
712 |     ) -> Vec<(KmerRef, u32)> {
    |               ^^^^^^^ the same lifetime is hidden here
    |
    = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
    |
712 |     ) -> Vec<(KmerRef<'_>, u32)> {
    |                      ++++

warning: hiding a lifetime that's elided elsewhere is confusing
   --> modkit-core/src/motifs/mod.rs:729:9
    |
729 |         &self,
    |         ^^^^^ the lifetime is elided here
...
732 |     ) -> Vec<(KmerRef, u32)> {
    |               ^^^^^^^ the same lifetime is hidden here
    |
    = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
    |
732 |     ) -> Vec<(KmerRef<'_>, u32)> {
    |                      ++++

warning: hiding a lifetime that's elided elsewhere is confusing
   --> modkit-core/src/motifs/mod.rs:737:9
    |
737 |         &self,
    |         ^^^^^ the lifetime is elided here
...
740 |     ) -> Vec<(KmerRef, u32)> {
    |               ^^^^^^^ the same lifetime is hidden here
    |
    = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
    |
740 |     ) -> Vec<(KmerRef<'_>, u32)> {
    |                      ++++

warning: hiding a lifetime that's elided elsewhere is confusing
   --> modkit-core/src/motifs/mod.rs:941:9
    |
941 |         &self,
    |         ^^^^^ the lifetime is elided here
...
944 |     ) -> Vec<(KmerRef, u32)> {
    |               ^^^^^^^ the same lifetime is hidden here
    |
    = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
    |
944 |     ) -> Vec<(KmerRef<'_>, u32)> {
    |                      ++++

warning: hiding a lifetime that's elided elsewhere is confusing
   --> modkit-core/src/motifs/mod.rs:954:9
    |
954 |         &self,
    |         ^^^^^ the lifetime is elided here
...
957 |     ) -> Vec<(KmerRef, u32)> {
    |               ^^^^^^^ the same lifetime is hidden here
    |
    = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
    |
957 |     ) -> Vec<(KmerRef<'_>, u32)> {
    |                      ++++

warning: hiding a lifetime that's elided elsewhere is confusing
   --> modkit-core/src/util.rs:542:9
    |
542 |         &self,
    |         ^^^^^ the lifetime is elided here
543 |         header: &HeaderView,
544 |     ) -> AnyhowResult<bam::FetchDefinition> {
    |                       ^^^^^^^^^^^^^^^^^^^^ the same lifetime is hidden here
    |
    = help: the same lifetime is referred to in inconsistent ways, making the signature confusing
help: use `'_` for type paths
    |
544 |     ) -> AnyhowResult<bam::FetchDefinition<'_>> {
    |                                           ++++

   Compiling ochm v0.1.0 (/Users/suhas/Downloads/modkit-0.5.0/ochm)
warning: `mod_kit` (lib) generated 10 warnings (run `cargo fix --lib -p mod_kit` to apply 10 suggestions)
   Compiling modkit v0.5.0 (/Users/suhas/Downloads/modkit-0.5.0/modkit)
    Finished `release` profile [optimized] target(s) in 1m 29s
```

**Comment by ArtRand** [comment]
Hello @SuhasSrinivasan, 

Those warnings are expected. With later versions of rustc these implicit lifetimes are considered warnings. Newer versions of the code have abided by these warnings. Is there a reason to be on v0.5.0?

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand ,

Thank you and not particularly. You mentioned in this thread on Dec 1:
> Yes, it's on my TODOs. For what it's worth, there isn't a v0.6.0 release of the tch and candle builds since the open chromatin module has not changed for v0.6.0.

So I was just sticking to v0.5.0, as I am using that in Linux and macOS.

**Comment by ArtRand** [comment]
@SuhasSrinivasan If a v0.6.1 release with the `tch` build would help I can get you that.

**Comment by SuhasSrinivasan** [comment]
Hi @ArtRand ,

Thank you and no worries for now, everything is working as expected with v0.5.0 in both Linux and macOS.
I noticed in the docs that v0.6.0+ has important changes to `pileup` algorithm and improved compute performance.
If v0.6.0+ is used for a study, do the previous v0.5.0 `pileup` bedMethyl files have to be recomputed?

**Comment by SuhasSrinivasan** [comment]
The macOS build script addresses a lot of the discussion here.
